
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon May 08 01:28:26 CEST 2017
//----------------------------------------------------

package fsb.parser;

import java_cup.runtime.*;
import fsb.ast.*;
import java.util.ArrayList;

/** CUP v0.11a beta 20060608 generated parser.
  * @version Mon May 08 01:28:26 CEST 2017
  */
public class parser extends java_cup.runtime.lr_parser {

  /** Default constructor. */
  public parser() {super();}

  /** Constructor which sets the default scanner. */
  public parser(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public parser(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\131\000\002\040\004\000\002\002\004\000\002\040" +
    "\005\000\002\002\004\000\002\003\005\000\002\003\004" +
    "\000\002\004\005\000\002\004\004\000\002\005\005\000" +
    "\002\005\003\000\002\006\004\000\002\006\003\000\002" +
    "\010\004\000\002\007\005\000\002\011\007\000\002\011" +
    "\006\000\002\011\004\000\002\011\003\000\002\012\003" +
    "\000\002\012\003\000\002\012\003\000\002\012\003\000" +
    "\002\012\003\000\002\012\003\000\002\012\003\000\002" +
    "\012\003\000\002\012\003\000\002\012\003\000\002\012" +
    "\003\000\002\012\003\000\002\012\003\000\002\012\003" +
    "\000\002\012\003\000\002\041\003\000\002\013\006\000" +
    "\002\014\006\000\002\014\006\000\002\036\003\000\002" +
    "\036\005\000\002\021\007\000\002\030\012\000\002\031" +
    "\013\000\002\015\005\000\002\015\005\000\002\016\006" +
    "\000\002\017\003\000\002\022\012\000\002\023\010\000" +
    "\002\024\006\000\002\020\003\000\002\025\003\000\002" +
    "\025\003\000\002\027\004\000\002\032\003\000\002\032" +
    "\003\000\002\032\003\000\002\032\005\000\002\032\005" +
    "\000\002\032\005\000\002\032\004\000\002\032\005\000" +
    "\002\032\005\000\002\032\005\000\002\032\005\000\002" +
    "\033\003\000\002\033\003\000\002\033\005\000\002\033" +
    "\005\000\002\033\005\000\002\033\005\000\002\037\006" +
    "\000\002\037\006\000\002\034\003\000\002\034\003\000" +
    "\002\034\003\000\002\034\005\000\002\034\005\000\002" +
    "\034\005\000\002\034\004\000\002\034\005\000\002\034" +
    "\005\000\002\034\005\000\002\034\005\000\002\035\003" +
    "\000\002\035\006\000\002\035\006\000\002\035\005\000" +
    "\002\035\003\000\002\035\005" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\277\000\004\031\007\001\002\000\004\002\301\001" +
    "\002\000\004\030\274\001\002\000\004\045\017\001\002" +
    "\000\006\016\011\061\012\001\002\000\006\016\014\020" +
    "\013\001\002\000\004\030\ufffc\001\002\000\006\016\ufff8" +
    "\020\ufff8\001\002\000\004\061\015\001\002\000\004\030" +
    "\ufffd\001\002\000\006\016\ufff9\020\ufff9\001\002\000\010" +
    "\002\001\044\261\046\263\001\002\000\006\060\023\062" +
    "\022\001\002\000\010\002\ufff6\044\ufff6\046\ufff6\001\002" +
    "\000\014\002\ufff5\044\ufff5\046\ufff5\060\253\062\022\001" +
    "\002\000\014\002\uffe0\044\uffe0\046\uffe0\060\uffe0\062\uffe0" +
    "\001\002\000\004\017\025\001\002\000\014\002\ufff0\044" +
    "\ufff0\046\ufff0\060\ufff0\062\ufff0\001\002\000\034\032\051" +
    "\033\060\034\037\036\062\037\036\040\026\041\040\042" +
    "\061\043\046\052\033\053\032\054\047\061\031\001\002" +
    "\000\004\061\247\001\002\000\004\016\uffe6\001\002\000" +
    "\004\016\246\001\002\000\004\021\235\001\002\000\004" +
    "\016\uffce\001\002\000\004\016\uffcf\001\002\000\004\016" +
    "\uffe3\001\002\000\004\016\uffe4\001\002\000\004\016\uffd0" +
    "\001\002\000\020\006\123\015\122\024\121\056\116\057" +
    "\120\060\072\061\073\001\002\000\004\061\223\001\002" +
    "\000\004\016\uffec\001\002\000\004\016\uffe1\001\002\000" +
    "\004\016\uffe7\001\002\000\004\016\uffeb\001\002\000\004" +
    "\016\uffe5\001\002\000\004\061\220\001\002\000\024\006" +
    "\163\015\162\022\164\024\161\051\154\056\156\057\160" +
    "\060\155\061\152\001\002\000\004\016\uffe8\001\002\000" +
    "\004\061\147\001\002\000\004\016\uffee\001\002\000\004" +
    "\016\uffe9\001\002\000\004\016\uffea\001\002\000\004\016" +
    "\uffef\001\002\000\004\016\uffe2\001\002\000\004\016\uffed" +
    "\001\002\000\006\022\065\061\067\001\002\000\004\061" +
    "\063\001\002\000\004\016\uffd4\001\002\000\004\020\064" +
    "\001\002\000\006\022\065\061\067\001\002\000\010\024" +
    "\074\060\072\061\073\001\002\000\004\020\070\001\002" +
    "\000\012\007\uffdc\016\uffdc\020\uffdc\021\uffdc\001\002\000" +
    "\010\024\074\060\072\061\073\001\002\000\012\004\076" +
    "\005\101\006\077\016\uffd2\001\002\000\036\004\uffc0\005" +
    "\uffc0\006\uffc0\007\uffc0\010\uffc0\011\uffc0\012\uffc0\013\uffc0" +
    "\014\uffc0\016\uffc0\020\uffc0\023\uffc0\025\uffc0\035\uffc0\001" +
    "\002\000\036\004\uffc1\005\uffc1\006\uffc1\007\uffc1\010\uffc1" +
    "\011\uffc1\012\uffc1\013\uffc1\014\uffc1\016\uffc1\020\uffc1\023" +
    "\uffc1\025\uffc1\035\uffc1\001\002\000\010\024\074\060\072" +
    "\061\073\001\002\000\012\004\076\005\101\006\077\025" +
    "\100\001\002\000\010\024\074\060\072\061\073\001\002" +
    "\000\010\024\074\060\072\061\073\001\002\000\036\004" +
    "\uffbf\005\uffbf\006\uffbf\007\uffbf\010\uffbf\011\uffbf\012\uffbf" +
    "\013\uffbf\014\uffbf\016\uffbf\020\uffbf\023\uffbf\025\uffbf\035" +
    "\uffbf\001\002\000\010\024\074\060\072\061\073\001\002" +
    "\000\036\004\uffbd\005\uffbd\006\077\007\uffbd\010\uffbd\011" +
    "\uffbd\012\uffbd\013\uffbd\014\uffbd\016\uffbd\020\uffbd\023\uffbd" +
    "\025\uffbd\035\uffbd\001\002\000\036\004\uffbc\005\uffbc\006" +
    "\uffbc\007\uffbc\010\uffbc\011\uffbc\012\uffbc\013\uffbc\014\uffbc" +
    "\016\uffbc\020\uffbc\023\uffbc\025\uffbc\035\uffbc\001\002\000" +
    "\036\004\uffbe\005\uffbe\006\077\007\uffbe\010\uffbe\011\uffbe" +
    "\012\uffbe\013\uffbe\014\uffbe\016\uffbe\020\uffbe\023\uffbe\025" +
    "\uffbe\035\uffbe\001\002\000\012\004\076\005\101\006\077" +
    "\023\106\001\002\000\012\007\uffdb\016\uffdb\020\uffdb\021" +
    "\uffdb\001\002\000\004\021\110\001\002\000\014\006\112" +
    "\024\074\055\113\060\072\061\073\001\002\000\012\004" +
    "\076\005\101\006\077\016\uffde\001\002\000\004\016\uffdd" +
    "\001\002\000\004\024\114\001\002\000\020\006\123\015" +
    "\122\024\121\056\116\057\120\060\072\061\073\001\002" +
    "\000\010\013\125\014\126\020\144\001\002\000\014\013" +
    "\uffcb\014\uffcb\020\uffcb\025\uffcb\035\uffcb\001\002\000\020" +
    "\004\076\005\101\006\077\007\134\010\136\011\135\012" +
    "\133\001\002\000\014\013\uffca\014\uffca\020\uffca\025\uffca" +
    "\035\uffca\001\002\000\020\006\123\015\122\024\121\056" +
    "\116\057\120\060\072\061\073\001\002\000\020\006\123" +
    "\015\122\024\121\056\116\057\120\060\072\061\073\001" +
    "\002\000\014\013\uffcc\014\uffcc\020\uffcc\025\uffcc\035\uffcc" +
    "\001\002\000\014\013\uffc6\014\uffc6\020\uffc6\025\uffc6\035" +
    "\uffc6\001\002\000\020\006\123\015\122\024\121\056\116" +
    "\057\120\060\072\061\073\001\002\000\020\006\123\015" +
    "\122\024\121\056\116\057\120\060\072\061\073\001\002" +
    "\000\014\013\125\014\uffc8\020\uffc8\025\uffc8\035\uffc8\001" +
    "\002\000\014\013\uffc7\014\uffc7\020\uffc7\025\uffc7\035\uffc7" +
    "\001\002\000\010\013\125\014\126\025\143\001\002\000" +
    "\022\004\076\005\101\006\077\007\134\010\136\011\135" +
    "\012\133\025\100\001\002\000\010\024\074\060\072\061" +
    "\073\001\002\000\010\024\074\060\072\061\073\001\002" +
    "\000\010\024\074\060\072\061\073\001\002\000\010\024" +
    "\074\060\072\061\073\001\002\000\022\004\076\005\101" +
    "\006\077\013\uffc4\014\uffc4\020\uffc4\025\uffc4\035\uffc4\001" +
    "\002\000\022\004\076\005\101\006\077\013\uffc3\014\uffc3" +
    "\020\uffc3\025\uffc3\035\uffc3\001\002\000\022\004\076\005" +
    "\101\006\077\013\uffc5\014\uffc5\020\uffc5\025\uffc5\035\uffc5" +
    "\001\002\000\022\004\076\005\101\006\077\013\uffc2\014" +
    "\uffc2\020\uffc2\025\uffc2\035\uffc2\001\002\000\014\013\uffc9" +
    "\014\uffc9\020\uffc9\025\uffc9\035\uffc9\001\002\000\020\006" +
    "\123\015\122\024\121\056\116\057\120\060\072\061\073" +
    "\001\002\000\010\013\125\014\126\025\146\001\002\000" +
    "\004\016\uffd8\001\002\000\004\021\150\001\002\000\006" +
    "\022\065\061\067\001\002\000\004\016\uffdf\001\002\000" +
    "\026\007\uffae\010\uffae\011\uffae\012\uffae\013\uffae\014\uffae" +
    "\016\uffae\023\uffae\025\uffae\026\215\001\002\000\010\013" +
    "\173\014\174\016\uffcd\001\002\000\004\026\212\001\002" +
    "\000\024\007\uffaa\010\uffaa\011\uffaa\012\uffaa\013\uffaa\014" +
    "\uffaa\016\uffaa\023\uffaa\025\uffaa\001\002\000\012\013\uffb8" +
    "\014\uffb8\016\uffb8\025\uffb8\001\002\000\012\007\202\010" +
    "\204\011\203\012\201\001\002\000\012\013\uffb7\014\uffb7" +
    "\016\uffb7\025\uffb7\001\002\000\024\006\163\015\162\022" +
    "\164\024\161\051\154\056\156\057\160\060\155\061\152" +
    "\001\002\000\024\006\163\015\162\022\164\024\161\051" +
    "\154\056\156\057\160\060\155\061\152\001\002\000\012" +
    "\013\uffb9\014\uffb9\016\uffb9\025\uffb9\001\002\000\014\022" +
    "\164\024\166\051\154\060\155\061\152\001\002\000\004" +
    "\023\171\001\002\000\014\022\164\024\166\051\154\060" +
    "\155\061\152\001\002\000\004\025\170\001\002\000\024" +
    "\007\uffa9\010\uffa9\011\uffa9\012\uffa9\013\uffa9\014\uffa9\016" +
    "\uffa9\023\uffa9\025\uffa9\001\002\000\024\007\uffab\010\uffab" +
    "\011\uffab\012\uffab\013\uffab\014\uffab\016\uffab\023\uffab\025" +
    "\uffab\001\002\000\012\013\uffb3\014\uffb3\016\uffb3\025\uffb3" +
    "\001\002\000\024\006\163\015\162\022\164\024\161\051" +
    "\154\056\156\057\160\060\155\061\152\001\002\000\024" +
    "\006\163\015\162\022\164\024\161\051\154\056\156\057" +
    "\160\060\155\061\152\001\002\000\012\013\173\014\uffb5" +
    "\016\uffb5\025\uffb5\001\002\000\012\013\uffb4\014\uffb4\016" +
    "\uffb4\025\uffb4\001\002\000\010\013\173\014\174\025\211" +
    "\001\002\000\014\007\202\010\204\011\203\012\201\025" +
    "\170\001\002\000\014\022\164\024\166\051\154\060\155" +
    "\061\152\001\002\000\014\022\164\024\166\051\154\060" +
    "\155\061\152\001\002\000\014\022\164\024\166\051\154" +
    "\060\155\061\152\001\002\000\014\022\164\024\166\051" +
    "\154\060\155\061\152\001\002\000\012\013\uffb1\014\uffb1" +
    "\016\uffb1\025\uffb1\001\002\000\012\013\uffb0\014\uffb0\016" +
    "\uffb0\025\uffb0\001\002\000\012\013\uffb2\014\uffb2\016\uffb2" +
    "\025\uffb2\001\002\000\012\013\uffaf\014\uffaf\016\uffaf\025" +
    "\uffaf\001\002\000\012\013\uffb6\014\uffb6\016\uffb6\025\uffb6" +
    "\001\002\000\004\060\213\001\002\000\004\027\214\001" +
    "\002\000\024\007\uffac\010\uffac\011\uffac\012\uffac\013\uffac" +
    "\014\uffac\016\uffac\023\uffac\025\uffac\001\002\000\004\060" +
    "\216\001\002\000\004\027\217\001\002\000\024\007\uffad" +
    "\010\uffad\011\uffad\012\uffad\013\uffad\014\uffad\016\uffad\023" +
    "\uffad\025\uffad\001\002\000\004\020\221\001\002\000\006" +
    "\022\065\061\067\001\002\000\004\016\uffd1\001\002\000" +
    "\004\020\224\001\002\000\006\022\065\061\067\001\002" +
    "\000\004\007\226\001\002\000\010\024\074\060\072\061" +
    "\073\001\002\000\012\004\076\005\101\006\077\020\230" +
    "\001\002\000\010\024\074\060\072\061\073\001\002\000" +
    "\012\004\076\005\101\006\077\016\uffd3\001\002\000\010" +
    "\013\125\014\126\035\233\001\002\000\004\060\234\001" +
    "\002\000\004\016\uffd5\001\002\000\014\006\237\024\074" +
    "\055\240\060\072\061\073\001\002\000\012\004\076\005" +
    "\101\006\077\016\uffd7\001\002\000\004\016\uffd6\001\002" +
    "\000\004\024\241\001\002\000\020\006\123\015\122\024" +
    "\121\056\116\057\120\060\072\061\073\001\002\000\010" +
    "\013\125\014\126\020\243\001\002\000\020\006\123\015" +
    "\122\024\121\056\116\057\120\060\072\061\073\001\002" +
    "\000\010\013\125\014\126\025\245\001\002\000\004\016" +
    "\uffd9\001\002\000\014\002\ufff2\044\ufff2\046\ufff2\060\ufff2" +
    "\062\ufff2\001\002\000\004\022\250\001\002\000\010\024" +
    "\074\060\072\061\073\001\002\000\012\004\076\005\101" +
    "\006\077\023\252\001\002\000\004\016\uffda\001\002\000" +
    "\004\017\255\001\002\000\014\002\ufff1\044\ufff1\046\ufff1" +
    "\060\ufff1\062\ufff1\001\002\000\034\032\051\033\060\034" +
    "\037\036\062\037\036\040\026\041\040\042\061\043\046" +
    "\052\033\053\032\054\047\061\031\001\002\000\004\016" +
    "\257\001\002\000\014\002\ufff3\044\ufff3\046\ufff3\060\ufff3" +
    "\062\ufff3\001\002\000\010\002\ufff7\044\ufff7\046\ufff7\001" +
    "\002\000\004\060\272\001\002\000\004\002\uffff\001\002" +
    "\000\006\047\264\050\265\001\002\000\024\006\163\015" +
    "\162\022\164\024\161\051\154\056\156\057\160\060\155" +
    "\061\152\001\002\000\024\006\163\015\162\022\164\024" +
    "\161\051\154\056\156\057\160\060\155\061\152\001\002" +
    "\000\010\013\173\014\174\016\267\001\002\000\004\002" +
    "\uffba\001\002\000\010\013\173\014\174\016\271\001\002" +
    "\000\004\002\uffbb\001\002\000\006\060\023\062\022\001" +
    "\002\000\014\002\ufff4\044\ufff4\046\ufff4\060\253\062\022" +
    "\001\002\000\006\016\277\061\012\001\002\000\004\045" +
    "\ufffe\001\002\000\006\016\300\020\013\001\002\000\004" +
    "\045\ufffa\001\002\000\004\045\ufffb\001\002\000\004\002" +
    "\000\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\277\000\010\002\005\003\004\040\003\001\001\000" +
    "\002\001\001\000\004\004\274\001\001\000\006\006\015" +
    "\010\017\001\001\000\004\005\007\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\006\007\257\037" +
    "\261\001\001\000\006\011\020\041\023\001\001\000\002" +
    "\001\001\000\004\041\253\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\042\012\027\013\054" +
    "\014\051\015\056\016\040\017\041\020\043\021\053\022" +
    "\052\023\047\024\042\025\026\026\044\027\034\030\033" +
    "\031\055\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\006\032\231\033\116\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\006" +
    "\034\152\035\156\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\004\036\106\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\004\036\065\001\001\000\004\033" +
    "\104\001\001\000\002\001\001\000\002\001\001\000\004" +
    "\033\070\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\004\033\074\001\001\000\002\001\001" +
    "\000\004\033\103\001\001\000\004\033\102\001\001\000" +
    "\002\001\001\000\004\033\101\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\004\033\110\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\006\032\114\033\116\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\006\032" +
    "\130\033\131\001\001\000\006\032\123\033\116\001\001" +
    "\000\002\001\001\000\002\001\001\000\006\032\127\033" +
    "\116\001\001\000\006\032\126\033\116\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\004\033\141\001\001\000\004\033\140\001\001" +
    "\000\004\033\137\001\001\000\004\033\136\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\006\032\144\033\116\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\004\036\150\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\006\034\176\035\177\001\001\000\006\034\171\035\156" +
    "\001\001\000\002\001\001\000\004\035\164\001\001\000" +
    "\002\001\001\000\004\035\166\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\006\034\175\035\156\001\001\000\006\034\174\035\156" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\004\035\207\001\001\000\004" +
    "\035\206\001\001\000\004\035\205\001\001\000\004\035" +
    "\204\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\004\036\221\001\001\000\002\001\001\000\002\001\001" +
    "\000\004\036\224\001\001\000\002\001\001\000\004\033" +
    "\226\001\001\000\002\001\001\000\004\033\230\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\004\033\235\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\006\032\241\033" +
    "\116\001\001\000\002\001\001\000\006\032\243\033\116" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\004\033\250\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\042\012\255\013\054\014\051\015\056\016\040" +
    "\017\041\020\043\021\053\022\052\023\047\024\042\025" +
    "\026\026\044\027\034\030\033\031\055\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\006\034\267" +
    "\035\156\001\001\000\006\034\265\035\156\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\006\011\272\041\023\001\001\000\004\041" +
    "\253\001\001\000\004\005\275\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$parser$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$parser$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$parser$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 1;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}


  /** Scan to get the next Symbol. */
  public java_cup.runtime.Symbol scan()
    throws java.lang.Exception
    {
 return lexer.next_token(); 
    }

 
  public boolean syntaxErrors;


  Lexer lexer;

  public parser(Lexer lex) {
      super(lex);
      lexer = lex;
  }

  
  public void report_error(String message, Object info) {
    syntaxErrors = true;
    
    System.out.println(message);
    
    if ( !(info instanceof Symbol) ) return;
    Symbol symbol = (Symbol) info;
    
    if ( symbol.left < 0 || symbol.right < 0 ) return;
    
    System.out.println(" at line " + symbol.left + ", column " + symbol.right);
  }

}

/** Cup generated class to encapsulate user supplied action code.*/
class CUP$parser$actions {
  private final parser parser;

  /** Constructor */
  CUP$parser$actions(parser parser) {
    this.parser = parser;
  }

  /** Method with the actual generated action code. */
  public final java_cup.runtime.Symbol CUP$parser$do_action(
    int                        CUP$parser$act_num,
    java_cup.runtime.lr_parser CUP$parser$parser,
    java.util.Stack            CUP$parser$stack,
    int                        CUP$parser$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$parser$result;

      /* select the action based on the action number */
      switch (CUP$parser$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 88: // assert_arit_expr ::= LEFTPAREN assert_arit_expr RIGHTPAREN 
            {
              AssertAritExpr RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		AssertAritExpr e = (AssertAritExpr)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		 RESULT = e; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("assert_arit_expr",27, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 87: // assert_arit_expr ::= NUMBER 
            {
              AssertAritExpr RESULT =null;
		int ileft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int iright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Integer i = (Integer)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = new AssertConstExpr(i); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("assert_arit_expr",27, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 86: // assert_arit_expr ::= LEFTBRACE assert_arit_expr RIGHTBRACE 
            {
              AssertAritExpr RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		AssertAritExpr a = (AssertAritExpr)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		 RESULT = new AssertIndirectGlobal(a); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("assert_arit_expr",27, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 85: // assert_arit_expr ::= PC LEFTCURLY NUMBER RIGHTCURLY 
            {
              AssertAritExpr RESULT =null;
		int pleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int pright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Integer p = (Integer)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		 RESULT = new AssertPC(p); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("assert_arit_expr",27, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 84: // assert_arit_expr ::= IDENT LEFTCURLY NUMBER RIGHTCURLY 
            {
              AssertAritExpr RESULT =null;
		int ileft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).left;
		int iright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).right;
		String i = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-3)).value;
		int pleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int pright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Integer p = (Integer)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		 RESULT = new AssertLocal(i, p); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("assert_arit_expr",27, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 83: // assert_arit_expr ::= IDENT 
            {
              AssertAritExpr RESULT =null;
		int ileft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int iright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		String i = (String)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = new AssertGlobal(i); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("assert_arit_expr",27, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 82: // assert_bool_expr ::= assert_arit_expr GREATER assert_arit_expr 
            {
              AssertBoolExpr RESULT =null;
		int lleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int lright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		AssertAritExpr l = (AssertAritExpr)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int rleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int rright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		AssertAritExpr r = (AssertAritExpr)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = new AssertComparsionBool(l, r, BoolExpr.BXType.GREATER); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("assert_bool_expr",26, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 81: // assert_bool_expr ::= assert_arit_expr LESS assert_arit_expr 
            {
              AssertBoolExpr RESULT =null;
		int lleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int lright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		AssertAritExpr l = (AssertAritExpr)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int rleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int rright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		AssertAritExpr r = (AssertAritExpr)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = new AssertComparsionBool(l, r, BoolExpr.BXType.LESS); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("assert_bool_expr",26, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 80: // assert_bool_expr ::= assert_arit_expr NEQ assert_arit_expr 
            {
              AssertBoolExpr RESULT =null;
		int lleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int lright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		AssertAritExpr l = (AssertAritExpr)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int rleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int rright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		AssertAritExpr r = (AssertAritExpr)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = new AssertComparsionBool(l, r, BoolExpr.BXType.NEQ); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("assert_bool_expr",26, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 79: // assert_bool_expr ::= assert_arit_expr EQUAL assert_arit_expr 
            {
              AssertBoolExpr RESULT =null;
		int lleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int lright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		AssertAritExpr l = (AssertAritExpr)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int rleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int rright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		AssertAritExpr r = (AssertAritExpr)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = new AssertComparsionBool(l, r, BoolExpr.BXType.EQUAL); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("assert_bool_expr",26, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 78: // assert_bool_expr ::= NOT assert_bool_expr 
            {
              AssertBoolExpr RESULT =null;
		int lleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int lright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		AssertBoolExpr l = (AssertBoolExpr)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = new AssertNotBool(l); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("assert_bool_expr",26, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 77: // assert_bool_expr ::= assert_bool_expr AND assert_bool_expr 
            {
              AssertBoolExpr RESULT =null;
		int lleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int lright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		AssertBoolExpr l = (AssertBoolExpr)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int rleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int rright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		AssertBoolExpr r = (AssertBoolExpr)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = new AssertComplexBool(l, r, BoolExpr.BXType.AND); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("assert_bool_expr",26, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 76: // assert_bool_expr ::= assert_bool_expr OR assert_bool_expr 
            {
              AssertBoolExpr RESULT =null;
		int lleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int lright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		AssertBoolExpr l = (AssertBoolExpr)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int rleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int rright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		AssertBoolExpr r = (AssertBoolExpr)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = new AssertComplexBool(l, r, BoolExpr.BXType.OR); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("assert_bool_expr",26, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 75: // assert_bool_expr ::= LEFTPAREN assert_bool_expr RIGHTPAREN 
            {
              AssertBoolExpr RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		AssertBoolExpr e = (AssertBoolExpr)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		 RESULT = e; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("assert_bool_expr",26, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 74: // assert_bool_expr ::= FALSE 
            {
              AssertBoolExpr RESULT =null;
		 RESULT = new AssertConstBool(false); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("assert_bool_expr",26, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 73: // assert_bool_expr ::= TRUE 
            {
              AssertBoolExpr RESULT =null;
		 RESULT = new AssertConstBool(true); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("assert_bool_expr",26, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 72: // assert_bool_expr ::= MUL 
            {
              AssertBoolExpr RESULT =null;
		 RESULT = new AssertConstBool(fsb.tvl.NondetBoolValue.getInstance()); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("assert_bool_expr",26, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 71: // assert_block ::= ASSERT ALWAYS assert_bool_expr SEMI 
            {
              Assert RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		AssertBoolExpr e = (AssertBoolExpr)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		 RESULT = new Assert(e, true); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("assert_block",29, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 70: // assert_block ::= ASSERT FINAL assert_bool_expr SEMI 
            {
              Assert RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		AssertBoolExpr e = (AssertBoolExpr)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		 RESULT = new Assert(e, false); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("assert_block",29, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 69: // arit_expr ::= arit_expr MUL arit_expr 
            {
              AritExpr RESULT =null;
		int lleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int lright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		AritExpr l = (AritExpr)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int rleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int rright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		AritExpr r = (AritExpr)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = new ComplexAritExpr(l, r, AritExpr.AXType.MUL); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("arit_expr",25, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 68: // arit_expr ::= arit_expr MINUS arit_expr 
            {
              AritExpr RESULT =null;
		int lleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int lright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		AritExpr l = (AritExpr)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int rleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int rright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		AritExpr r = (AritExpr)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = new ComplexAritExpr(l, r, AritExpr.AXType.MINUS); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("arit_expr",25, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 67: // arit_expr ::= arit_expr PLUS arit_expr 
            {
              AritExpr RESULT =null;
		int lleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int lright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		AritExpr l = (AritExpr)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int rleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int rright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		AritExpr r = (AritExpr)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = new ComplexAritExpr(l, r, AritExpr.AXType.PLUS); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("arit_expr",25, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 66: // arit_expr ::= LEFTPAREN arit_expr RIGHTPAREN 
            {
              AritExpr RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		AritExpr e = (AritExpr)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		 RESULT = e; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("arit_expr",25, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 65: // arit_expr ::= NUMBER 
            {
              AritExpr RESULT =null;
		int ileft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int iright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Integer i = (Integer)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = new ConstExpr(i); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("arit_expr",25, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 64: // arit_expr ::= IDENT 
            {
              AritExpr RESULT =null;
		int ileft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int iright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		String i = (String)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = new LocalExpr(i); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("arit_expr",25, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 63: // bool_expr ::= arit_expr GREATER arit_expr 
            {
              BoolExpr RESULT =null;
		int lleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int lright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		AritExpr l = (AritExpr)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int rleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int rright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		AritExpr r = (AritExpr)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = new ComparsionBool(l, r, BoolExpr.BXType.GREATER); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("bool_expr",24, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 62: // bool_expr ::= arit_expr LESS arit_expr 
            {
              BoolExpr RESULT =null;
		int lleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int lright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		AritExpr l = (AritExpr)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int rleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int rright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		AritExpr r = (AritExpr)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = new ComparsionBool(l, r, BoolExpr.BXType.LESS); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("bool_expr",24, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 61: // bool_expr ::= arit_expr NEQ arit_expr 
            {
              BoolExpr RESULT =null;
		int lleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int lright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		AritExpr l = (AritExpr)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int rleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int rright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		AritExpr r = (AritExpr)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = new ComparsionBool(l, r, BoolExpr.BXType.NEQ); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("bool_expr",24, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 60: // bool_expr ::= arit_expr EQUAL arit_expr 
            {
              BoolExpr RESULT =null;
		int lleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int lright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		AritExpr l = (AritExpr)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int rleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int rright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		AritExpr r = (AritExpr)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = new ComparsionBool(l, r, BoolExpr.BXType.EQUAL); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("bool_expr",24, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 59: // bool_expr ::= NOT bool_expr 
            {
              BoolExpr RESULT =null;
		int lleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int lright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		BoolExpr l = (BoolExpr)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = new NotBool(l); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("bool_expr",24, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 58: // bool_expr ::= bool_expr AND bool_expr 
            {
              BoolExpr RESULT =null;
		int lleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int lright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		BoolExpr l = (BoolExpr)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int rleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int rright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		BoolExpr r = (BoolExpr)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = new ComplexBool(l, r, BoolExpr.BXType.AND); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("bool_expr",24, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 57: // bool_expr ::= bool_expr OR bool_expr 
            {
              BoolExpr RESULT =null;
		int lleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int lright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		BoolExpr l = (BoolExpr)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int rleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int rright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		BoolExpr r = (BoolExpr)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = new ComplexBool(l, r, BoolExpr.BXType.OR); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("bool_expr",24, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 56: // bool_expr ::= LEFTPAREN bool_expr RIGHTPAREN 
            {
              BoolExpr RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		BoolExpr e = (BoolExpr)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		 RESULT = e; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("bool_expr",24, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 55: // bool_expr ::= FALSE 
            {
              BoolExpr RESULT =null;
		 RESULT = new ConstBool(false); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("bool_expr",24, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 54: // bool_expr ::= TRUE 
            {
              BoolExpr RESULT =null;
		 RESULT = new ConstBool(true); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("bool_expr",24, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 53: // bool_expr ::= MUL 
            {
              BoolExpr RESULT =null;
		 RESULT = new NondetBool(); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("bool_expr",24, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 52: // assume_stat ::= ASSUME assert_bool_expr 
            {
              Statement RESULT =null;
		int condleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int condright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		AssertBoolExpr cond = (AssertBoolExpr)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = new Assume(cond); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("assume_stat",21, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 51: // begin_atomic_stat ::= ENDATOMIC 
            {
              Statement RESULT =null;
		 RESULT = new EndAtomic(); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("begin_atomic_stat",19, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 50: // begin_atomic_stat ::= BEGINATOMIC 
            {
              Statement RESULT =null;
		 RESULT = new BeginAtomic(); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("begin_atomic_stat",19, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 49: // nop_stat ::= NOP 
            {
              Statement RESULT =null;
		 RESULT = new Nop(); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("nop_stat",14, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 48: // dec_stat ::= ATOMICDEC IDENT COMMA shared_val 
            {
              Statement RESULT =null;
		int dstleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int dstright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		String dst = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int sharedleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int sharedright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		SharedVal shared = (SharedVal)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = new AtomicDec(dst, shared); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("dec_stat",18, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 47: // swap_stat ::= SWAP IDENT COMMA shared_val COMMA arit_expr 
            {
              Statement RESULT =null;
		int dstleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)).left;
		int dstright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)).right;
		String dst = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-4)).value;
		int sharedleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int sharedright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		SharedVal shared = (SharedVal)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int newvalleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int newvalright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		AritExpr newval = (AritExpr)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = new Swap(dst, shared, newval); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("swap_stat",17, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 46: // cas_stat ::= CAS IDENT COMMA shared_val EQUAL arit_expr COMMA arit_expr 
            {
              Statement RESULT =null;
		int dstleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-6)).left;
		int dstright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-6)).right;
		String dst = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-6)).value;
		int sharedleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)).left;
		int sharedright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)).right;
		SharedVal shared = (SharedVal)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-4)).value;
		int valleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int valright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		AritExpr val = (AritExpr)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int newvalleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int newvalright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		AritExpr newval = (AritExpr)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = new CAS(dst, shared, val, newval); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("cas_stat",16, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-7)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 45: // barrier_stat ::= BARRIER 
            {
              Statement RESULT =null;
		 RESULT = new Barrier(); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("barrier_stat",13, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 44: // branch_stat ::= IF bool_expr GOTO NUMBER 
            {
              Statement RESULT =null;
		int condleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int condright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		BoolExpr cond = (BoolExpr)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int labelleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int labelright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Integer label = (Integer)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = new Branch(cond, label); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("branch_stat",12, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 43: // assign_stat ::= IDENT ASSIGN MUL 
            {
              Statement RESULT =null;
		int dstleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int dstright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		String dst = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		 RESULT = new Assign(new NondetArit(), dst); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("assign_stat",11, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 42: // assign_stat ::= IDENT ASSIGN arit_expr 
            {
              Statement RESULT =null;
		int dstleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int dstright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		String dst = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int srcleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int srcright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		AritExpr src = (AritExpr)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = new Assign(src, dst); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("assign_stat",11, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 41: // choose_store_stat ::= STORE shared_val ASSIGN CHOOSE LEFTPAREN bool_expr COMMA bool_expr RIGHTPAREN 
            {
              Statement RESULT =null;
		int dstleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-7)).left;
		int dstright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-7)).right;
		SharedVal dst = (SharedVal)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-7)).value;
		int b1left = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).left;
		int b1right = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).right;
		BoolExpr b1 = (BoolExpr)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-3)).value;
		int b2left = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int b2right = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		BoolExpr b2 = (BoolExpr)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		 RESULT = new ChooseStore(b1,b2, dst); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("choose_store_stat",23, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-8)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 40: // choose_assign_stat ::= IDENT ASSIGN CHOOSE LEFTPAREN bool_expr COMMA bool_expr RIGHTPAREN 
            {
              Statement RESULT =null;
		int dstleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-7)).left;
		int dstright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-7)).right;
		String dst = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-7)).value;
		int b1left = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).left;
		int b1right = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).right;
		BoolExpr b1 = (BoolExpr)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-3)).value;
		int b2left = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int b2right = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		BoolExpr b2 = (BoolExpr)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		 RESULT = new ChooseAssign(b1,b2, dst); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("choose_assign_stat",22, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-7)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 39: // allocate_stat ::= ALLOCATE IDENT LEFTBRACE arit_expr RIGHTBRACE 
            {
              Statement RESULT =null;
		int dstleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).left;
		int dstright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).right;
		String dst = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-3)).value;
		int numleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int numright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		AritExpr num = (AritExpr)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		 RESULT = new Allocate(dst, num); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("allocate_stat",15, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 38: // shared_val ::= LEFTBRACE arit_expr RIGHTBRACE 
            {
              SharedVal RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		AritExpr a = (AritExpr)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		 RESULT = new DerefSharedVal(a); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("shared_val",28, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 37: // shared_val ::= IDENT 
            {
              SharedVal RESULT =null;
		int ileft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int iright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		String i = (String)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = new PrimitiveSharedVal(i); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("shared_val",28, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 36: // store_stat ::= STORE shared_val ASSIGN MUL 
            {
              Statement RESULT =null;
		int dstleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int dstright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		SharedVal dst = (SharedVal)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		 RESULT = new Store(new NondetArit(), dst); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("store_stat",10, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 35: // store_stat ::= STORE shared_val ASSIGN arit_expr 
            {
              Statement RESULT =null;
		int dstleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int dstright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		SharedVal dst = (SharedVal)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int srcleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int srcright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		AritExpr src = (AritExpr)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = new Store(src, dst); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("store_stat",10, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 34: // load_stat ::= LOAD IDENT ASSIGN shared_val 
            {
              Statement RESULT =null;
		int dstleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int dstright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		String dst = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int srcleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int srcright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		SharedVal src = (SharedVal)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = new Load(src, dst); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("load_stat",9, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 33: // c_comment ::= C_COMMENT 
            {
              Comment RESULT =null;
		int sleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int sright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		String s = (String)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = new Comment(s); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("c_comment",31, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 32: // statement ::= barrier_stat 
            {
              Statement RESULT =null;
		int sleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int sright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Statement s = (Statement)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = s; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("statement",8, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 31: // statement ::= choose_store_stat 
            {
              Statement RESULT =null;
		int sleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int sright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Statement s = (Statement)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = s; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("statement",8, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 30: // statement ::= choose_assign_stat 
            {
              Statement RESULT =null;
		int sleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int sright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Statement s = (Statement)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = s; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("statement",8, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 29: // statement ::= assume_stat 
            {
              Statement RESULT =null;
		int sleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int sright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Statement s = (Statement)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = s; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("statement",8, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 28: // statement ::= end_atomic_stat 
            {
              Statement RESULT =null;
		int sleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int sright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Statement s = (Statement)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = s; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("statement",8, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 27: // statement ::= begin_atomic_stat 
            {
              Statement RESULT =null;
		int sleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int sright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Statement s = (Statement)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = s; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("statement",8, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 26: // statement ::= dec_stat 
            {
              Statement RESULT =null;
		int sleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int sright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Statement s = (Statement)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = s; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("statement",8, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 25: // statement ::= swap_stat 
            {
              Statement RESULT =null;
		int sleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int sright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Statement s = (Statement)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = s; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("statement",8, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 24: // statement ::= cas_stat 
            {
              Statement RESULT =null;
		int sleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int sright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Statement s = (Statement)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = s; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("statement",8, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 23: // statement ::= allocate_stat 
            {
              Statement RESULT =null;
		int sleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int sright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Statement s = (Statement)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = s; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("statement",8, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 22: // statement ::= nop_stat 
            {
              Statement RESULT =null;
		int sleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int sright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Statement s = (Statement)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = s; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("statement",8, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 21: // statement ::= branch_stat 
            {
              Statement RESULT =null;
		int sleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int sright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Statement s = (Statement)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = s; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("statement",8, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // statement ::= assign_stat 
            {
              Statement RESULT =null;
		int sleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int sright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Statement s = (Statement)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = s; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("statement",8, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // statement ::= store_stat 
            {
              Statement RESULT =null;
		int sleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int sright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Statement s = (Statement)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = s; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("statement",8, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // statement ::= load_stat 
            {
              Statement RESULT =null;
		int sleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int sright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Statement s = (Statement)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = s; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("statement",8, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // stat_list ::= c_comment 
            {
              ArrayList<Statement> RESULT =null;
		int sleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int sright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Comment s = (Comment)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = new ArrayList<Statement>(); RESULT.add(s); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("stat_list",7, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // stat_list ::= stat_list c_comment 
            {
              ArrayList<Statement> RESULT =null;
		int lleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int lright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		ArrayList<Statement> l = (ArrayList<Statement>)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		int sleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int sright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Comment s = (Comment)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 if(l.size()>1) {s.setLabel(l.get(l.size()-1).getLabel());};l.add(s); RESULT = l; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("stat_list",7, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // stat_list ::= NUMBER COLON statement SEMI 
            {
              ArrayList<Statement> RESULT =null;
		int ileft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).left;
		int iright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).right;
		Integer i = (Integer)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-3)).value;
		int sleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int sright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Statement s = (Statement)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		 RESULT = new ArrayList<Statement>(); s.setLabel(i); RESULT.add(s); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("stat_list",7, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // stat_list ::= stat_list NUMBER COLON statement SEMI 
            {
              ArrayList<Statement> RESULT =null;
		int lleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)).left;
		int lright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)).right;
		ArrayList<Statement> l = (ArrayList<Statement>)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-4)).value;
		int ileft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).left;
		int iright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).right;
		Integer i = (Integer)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-3)).value;
		int sleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int sright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Statement s = (Statement)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		 s.setLabel(i); l.add(s); RESULT = l; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("stat_list",7, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // proc ::= PROCESS NUMBER stat_list 
            {
              Code RESULT =null;
		int nleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int nright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Integer n = (Integer)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		int sleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int sright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		ArrayList<Statement> s = (ArrayList<Statement>)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 Statement end = new End(); end.setLabel(-1); s.add(end); RESULT = new Code(n, s); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("proc",5, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // init_code ::= INIT stat_list 
            {
              Code RESULT =null;
		int sleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int sright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		ArrayList<Statement> s = (ArrayList<Statement>)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 Statement barrier = new Barrier(); barrier.setLabel(-2); s.add(barrier); 
	  Statement end = new End(); end.setLabel(-1); s.add(end); RESULT = new Code(0, s); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("init_code",6, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // code_area ::= init_code 
            {
              ArrayList<Code> RESULT =null;
		int pleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int pright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Code p = (Code)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = new ArrayList<Code>(); RESULT.add(p); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("code_area",4, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // code_area ::= code_area proc 
            {
              ArrayList<Code> RESULT =null;
		int cleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int cright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		ArrayList<Code> c = (ArrayList<Code>)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		int pleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int pright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Code p = (Code)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 c.add(p); RESULT = c; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("code_area",4, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // var_list ::= IDENT 
            {
              ArrayList<String> RESULT =null;
		int ileft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int iright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		String i = (String)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = new ArrayList<String>(); RESULT.add(i); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("var_list",3, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // var_list ::= var_list COMMA IDENT 
            {
              ArrayList<String> RESULT =null;
		int vleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int vright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		ArrayList<String> v = (ArrayList<String>)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int ileft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int iright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		String i = (String)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 v.add(i); RESULT = v; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("var_list",3, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // local_decl ::= LOCAL SEMI 
            {
              ArrayList<String> RESULT =null;
		 RESULT = new ArrayList<String>(); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("local_decl",2, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // local_decl ::= LOCAL var_list SEMI 
            {
              ArrayList<String> RESULT =null;
		int vleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int vright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		ArrayList<String> v = (ArrayList<String>)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		 RESULT = v; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("local_decl",2, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // shared_decl ::= SHARED SEMI 
            {
              ArrayList<String> RESULT =null;
		 RESULT = new ArrayList<String>(); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("shared_decl",1, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // shared_decl ::= SHARED var_list SEMI 
            {
              ArrayList<String> RESULT =null;
		int vleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int vright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		ArrayList<String> v = (ArrayList<String>)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		 RESULT = v; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("shared_decl",1, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // decl_area ::= shared_decl local_decl 
            {
              Declarations RESULT =null;
		int sleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int sright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		ArrayList<String> s = (ArrayList<String>)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		int lleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int lright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		ArrayList<String> l = (ArrayList<String>)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = new Declarations(s, l); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("decl_area",0, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // program ::= decl_area code_area assert_block 
            {
              MProgram RESULT =null;
		int dleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int dright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Declarations d = (Declarations)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int cleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int cright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		ArrayList<Code> c = (ArrayList<Code>)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		int aleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int aright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Assert a = (Assert)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = new MProgram(d, c, a); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("program",30, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // $START ::= program EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		MProgram start_val = (MProgram)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		RESULT = start_val;
              CUP$parser$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$parser$parser.done_parsing();
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // program ::= decl_area code_area 
            {
              MProgram RESULT =null;
		int dleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int dright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Declarations d = (Declarations)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		int cleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int cright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		ArrayList<Code> c = (ArrayList<Code>)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = new MProgram(d, c); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("program",30, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number found in internal parse table");

        }
    }
}

