
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sat Jun 25 14:41:38 IDT 2016
//----------------------------------------------------

package fsb.parser;

/** CUP generated class containing symbol constants. */
public class pred_sym {
  /* terminals */
  public static final int AND = 8;
  public static final int IDENT = 17;
  public static final int PLUS = 2;
  public static final int OR = 9;
  public static final int NOT = 10;
  public static final int GREATER = 7;
  public static final int TRUE = 14;
  public static final int EOF = 0;
  public static final int NUMBER = 16;
  public static final int FALSE = 15;
  public static final int MINUS = 3;
  public static final int error = 1;
  public static final int ASSIGN = 11;
  public static final int LEFTPAREN = 12;
  public static final int RIGHTPAREN = 13;
  public static final int MUL = 4;
  public static final int NEQ = 5;
  public static final int LESS = 6;
}

