
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun Apr 17 01:42:33 IDT 2016
//----------------------------------------------------

package fsb.parser;

/** CUP generated class containing symbol constants. */
public class st_sym {
  /* terminals */
  public static final int BARRIER = 31;
  public static final int GE = 10;
  public static final int LOAD = 27;
  public static final int STORE = 28;
  public static final int CAS = 34;
  public static final int C_COMMENT_S = 47;
  public static final int RIGHTPAREN = 24;
  public static final int ASSUME = 45;
  public static final int PC = 40;
  public static final int GREATER = 8;
  public static final int SEMI = 16;
  public static final int ENDATOMIC = 44;
  public static final int ASSERT = 37;
  public static final int LESS = 7;
  public static final int MINUS = 3;
  public static final int LEFTPAREN = 23;
  public static final int C_COMMENT_F = 48;
  public static final int NOT = 15;
  public static final int AND = 11;
  public static final int CHOOSE = 46;
  public static final int ST_RESRV_W = 50;
  public static final int NOP = 32;
  public static final int OR = 12;
  public static final int COMMA = 18;
  public static final int PLUS = 2;
  public static final int ASSIGN = 20;
  public static final int IF = 29;
  public static final int DOT = 19;
  public static final int LE = 9;
  public static final int EOF = 0;
  public static final int EQUAL = 5;
  public static final int TRUE = 51;
  public static final int RIGHTCURLY = 26;
  public static final int error = 1;
  public static final int MUL = 4;
  public static final int OR2 = 14;
  public static final int NUMBER = 53;
  public static final int NEQ = 6;
  public static final int IDENT = 54;
  public static final int ATOMICDEC = 36;
  public static final int LEFTCURLY = 25;
  public static final int RIGHTBRACE = 22;
  public static final int COLON = 17;
  public static final int ELSE = 41;
  public static final int ALLOCATE = 33;
  public static final int GOTO = 30;
  public static final int FINAL = 38;
  public static final int LEFTBRACE = 21;
  public static final int THEN = 42;
  public static final int BEGINATOMIC = 43;
  public static final int FALSE = 52;
  public static final int CPP_COMMENT_S = 49;
  public static final int AND2 = 13;
  public static final int SWAP = 35;
  public static final int ALWAYS = 39;
}

